Try to improve support for py32f002a
creatoy/py32f0xx-hal pull request #1
Opened 2024-06-12 21:34 UTC by usbalbin

This is not yet tested on real hardware. So for this is just an attempt to get the code to compile with the device feature `py32f002a`.

2024-06-13 07:30 UTC, creatoy requested changes
Thanks for your contrib. I'm not have a real py32f002a dev board now, So I can not test it as well. It would be even better if you could test it on a real chip.

2024-06-13 07:30 UTC, creatoy commented on src/serial.rs
> +use crate::gpio::{AF3, AF4, AF8, AF9};
AF8 reimported here

2024-06-13 18:49 UTC, usbalbin commented
This now runs successfully(but with some warnings)
```bash
cargo c --features py32f030 && cargo c --features py32f003 && cargo c --features py32f002a
```

2024-06-13 19:15 UTC, usbalbin commented on src/serial.rs
> +use crate::gpio::{AF3, AF4, AF8, AF9};
Oh sorry, fixed

2024-06-14 02:36 UTC, creatoy approved these changes

2024-06-14 02:47 UTC, merged